name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: -s check

    - name: Store integration test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: integration-test-report
        path: ${{ github.workspace }}/build/test-results/test/
        retention-days: 1
